import { solidityTypeToGraphQL, safeFieldName, AbiEvent } from './solidityToGraphQL'

export interface SubgraphConfig {
  contractName: string
  contractAddress: string
  network: string
  startBlock: number
  abi: any[]
  selectedEvents: string[] // event names to index
  subgraphName: string
}

// Remix chain ID → The Graph network name
const CHAIN_ID_TO_NETWORK: Record<number, string> = {
  1: 'mainnet',
  11155111: 'sepolia',
  17000: 'holesky',
  137: 'matic',
  80001: 'mumbai',
  42161: 'arbitrum-one',
  421614: 'arbitrum-sepolia',
  10: 'optimism',
  11155420: 'optimism-sepolia',
  8453: 'base',
  84532: 'base-sepolia',
  100: 'gnosis',
  56: 'bsc',
  43114: 'avalanche',
  250: 'fantom',
  1101: 'polygon-zkevm',
}

export function chainIdToGraphNetwork(chainId: number): string {
  return CHAIN_ID_TO_NETWORK[chainId] || 'mainnet'
}

function generateSchema(events: AbiEvent[]): string {
  const entities = events.map(event => {
    const fields = [
      '  id: Bytes!',
      ...event.inputs.map((input, i) => {
        const fieldName = safeFieldName(input.name, i)
        const gqlType = solidityTypeToGraphQL(input.type)
        return `  ${fieldName}: ${gqlType}!`
      }),
      '  blockNumber: BigInt!',
      '  blockTimestamp: BigInt!',
      '  transactionHash: Bytes!'
    ]
    return `type ${event.name} @entity(immutable: true) {\n${fields.join('\n')}\n}`
  })
  return entities.join('\n\n')
}

function generateMappings(contractName: string, events: AbiEvent[]): string {
  const importTypes = events.map(e => `${e.name} as ${e.name}Event`).join(',\n  ')
  const importEntities = events.map(e => e.name).join(', ')

  const handlers = events.map(event => {
    const paramAssignments = event.inputs.map((input, i) => {
      const fieldName = safeFieldName(input.name, i)
      return `  entity.${fieldName} = event.params.${input.name || `param${i}`}`
    }).join('\n')

    return `export function handle${event.name}(event: ${event.name}Event): void {
  let entity = new ${event.name}(
    event.transaction.hash.concatI32(event.logIndex.toI32())
  )
${paramAssignments}
  entity.blockNumber = event.block.number
  entity.blockTimestamp = event.block.timestamp
  entity.transactionHash = event.transaction.hash
  entity.save()
}`
  })

  return `import {
  ${importTypes}
} from "../generated/${contractName}/${contractName}"
import { ${importEntities} } from "../generated/schema"

${handlers.join('\n\n')}`
}

function generateManifest(config: SubgraphConfig, events: AbiEvent[]): string {
  const eventHandlers = events.map(e => {
    const signature = `${e.name}(${e.inputs.map(i => `${i.indexed ? 'indexed ' : ''}${i.type}`).join(',')})`
    return `        - event: ${signature}
          handler: handle${e.name}`
  }).join('\n')

  const entityNames = events.map(e => `        - ${e.name}`).join('\n')

  return `specVersion: 1.3.0
description: Subgraph for ${config.contractName} on ${config.network}
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: ${config.contractName}
    network: ${config.network}
    source:
      address: "${config.contractAddress}"
      abi: ${config.contractName}
      startBlock: ${config.startBlock}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
${entityNames}
      abis:
        - name: ${config.contractName}
          file: ./abis/${config.contractName}.json
      eventHandlers:
${eventHandlers}
      file: ./src/mapping.ts`
}

function generatePackageJson(subgraphName: string): string {
  return JSON.stringify({
    name: subgraphName,
    version: '0.0.1',
    scripts: {
      codegen: 'graph codegen',
      build: 'graph build',
      deploy: `graph deploy --studio ${subgraphName}`,
      'create-local': `graph create --node http://localhost:8020/ ${subgraphName}`,
      'deploy-local': `graph deploy --node http://localhost:8020/ --ipfs http://localhost:5001 ${subgraphName}`
    },
    dependencies: {
      '@graphprotocol/graph-cli': '^0.81.0',
      '@graphprotocol/graph-ts': '^0.35.1'
    }
  }, null, 2)
}

function generateReadme(config: SubgraphConfig): string {
  return `# ${config.subgraphName}

Subgraph generated by Remix IDE for **${config.contractName}** on \`${config.network}\`.

- Contract: \`${config.contractAddress}\`
- Start block: \`${config.startBlock}\`

## Setup

Open the Remix terminal and run:

\`\`\`bash
cd subgraphs/${config.subgraphName}
npm install
\`\`\`

## Authenticate with Subgraph Studio

\`\`\`bash
npx graph auth --studio <YOUR_DEPLOY_KEY>
\`\`\`

Get your deploy key at https://thegraph.com/studio/

## Generate Types & Build

\`\`\`bash
npx graph codegen && npx graph build
\`\`\`

## Deploy

\`\`\`bash
npx graph deploy --studio ${config.subgraphName}
\`\`\`

## Query

Once deployed, your subgraph endpoint will be:
\`https://api.studio.thegraph.com/query/<ID>/${config.subgraphName}/v0.0.1\`

Use the **Query Playground** tab in the Remix The Graph panel to run GraphQL queries.
`
}

export interface GeneratedSubgraphFiles {
  [path: string]: string
}

export function generateSubgraphProject(config: SubgraphConfig): GeneratedSubgraphFiles {
  const events = config.abi
    .filter((item: any) => item.type === 'event' && config.selectedEvents.includes(item.name))

  const base = `subgraphs/${config.subgraphName}`

  return {
    [`${base}/subgraph.yaml`]: generateManifest(config, events),
    [`${base}/schema.graphql`]: generateSchema(events),
    [`${base}/src/mapping.ts`]: generateMappings(config.contractName, events),
    [`${base}/abis/${config.contractName}.json`]: JSON.stringify(config.abi, null, 2),
    [`${base}/package.json`]: generatePackageJson(config.subgraphName),
    [`${base}/README.md`]: generateReadme(config)
  }
}
